name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: deploy app
        with:
          port: 22
          script: |
            cd actions-runner/_work/crm/crm
            git pull origin master
            git status
            npm install
            npm run build
            pm2 restart all
