name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: stop the server
        run: echo "stopping the server"
      - name: collect necessary library
        run: npm install
      - name: install pm2
        run: npm i pm2
      - name: prepare an optimistic production build
        run: npm run build
      - name: run the server
        run: pm2 start dist/main.js
