name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: stop the server
        run:  echo "stopping the server"
      - name: install package
        run: npm install
      - name: building the optimistic build
        run: npm run build
      - name: start the serve
        run: pm2 start dist/main.js
